// Native floating-point bit representation without numerical conversion.

noescape extern:"intrinsic" fun ablaBitF64ToI64(value: f64): int
noescape extern:"intrinsic" fun ablaBitI64ToF64(value: int): f64
noescape extern:"intrinsic" fun ablaConvertI64ToF64(value: int): f64
noescape extern:"intrinsic" fun ablaBitF32ToI32(value: f32): int
noescape extern:"intrinsic" fun ablaBitI32ToF32(value: int): f32
noescape extern:"intrinsic" fun ablaConvertU32ToF32(value: u32): f32
noescape extern:"intrinsic" fun ablaConvertI32ToF32(value: i32): f32
noescape extern:"intrinsic" fun ablaConvertF32ToU32(value: f32): u32
noescape extern:"intrinsic" fun ablaConvertF32ToI32(value: f32): i32

fun f64ToBits(value: f64): int = ablaBitF64ToI64(value)

fun f64FromBits(value: int): f64 = ablaBitI64ToF64(value)

fun f64FromInt(value: int): f64 = ablaConvertI64ToF64(value)

fun f32ToBits(value: f32): u32 = u32(ablaBitF32ToI32(value))

fun f32FromBits(value: u32): f32 = ablaBitI32ToF32(int(value))

fun f32FromU32(value: u32): f32 = ablaConvertU32ToF32(value)

fun f32FromI32(value: i32): f32 = ablaConvertI32ToF32(value)

fun f32ToU32(value: f32): u32 = ablaConvertF32ToU32(value)

fun f32ToI32(value: f32): i32 = ablaConvertF32ToI32(value)
