// Native floating-point bit representation without numerical conversion.

noescape extern:"intrinsic" fun ablaBitF64ToI64(value: f64): int
noescape extern:"intrinsic" fun ablaBitI64ToF64(value: int): f64
noescape extern:"intrinsic" fun ablaConvertI64ToF64(value: int): f64

fun f64ToBits(value: f64): int = ablaBitF64ToI64(value)

fun f64FromBits(value: int): f64 = ablaBitI64ToF64(value)

fun f64FromInt(value: int): f64 = ablaConvertI64ToF64(value)
