import "abla/sys/linux/process"

class Command(val native: LinuxCommand)

class ChildProcess(val native: LinuxChildProcess)

fun command(executable: string): Command =
    Command(linuxCommand(executable))

fun Command.argument(value: string): Command {
    this.native.argument(value)
    this
}

fun Command.run(): int = this.native.run()

fun Command.captureText(): string = this.native.captureText()

fun Command.start(): ChildProcess = ChildProcess(this.native.start())

fun ChildProcess.stop(graceMilliseconds: int = 5000): int =
    this.native.stop(graceMilliseconds)
