import "abla/http"
import "abla/sys/linux/io"
import "abla/sys/linux/process"

fun slow(request: HttpRequest): HttpResponse {
    linuxPrintStandardError("request-start-v2\n")
    linuxSleep(1500)
    httpText("slow-v2")
}

fun main: int {
    val router = httpRouter()
    router.get("/slow", slow)
    val listener = tcpListen(0)
    linuxPrintStandardError("${listener.localPort()}\n")
    serveHttpOnListener(router, listener)
}
