resource class Ticket(val value: int)
class TicketBox(var ticket: Ticket)
class TicketShelf(val boxes: array<TicketBox>)

fun inspectShelf(shelf: TicketShelf): int = shelf.boxes[0].ticket.value

fun replaceDifferentIndex(movedIndex: int, assignedIndex: int): int {
    val shelf = TicketShelf([
        TicketBox(Ticket(40)),
        TicketBox(Ticket(1))
    ])
    val ticket = move(shelf.boxes[movedIndex].ticket)
    shelf.boxes[assignedIndex].ticket = Ticket(0)
    ticket.value + inspectShelf(shelf)
}

fun main: int = replaceDifferentIndex(0, 1)
