#import("abla/compiler")

#compilerGrant("process.io")
#compilerGrant("clock")
#compilerGrant("random")

val buildClock = #compilerClockMilliseconds()
val buildRandom = #compilerRandomInteger(1000000)
val processStatus = #compilerRunProcess(["true"])

fun main: int {
    if (processStatus != 0) 11
    else if (buildClock <= 0) 12
    else if (buildRandom < 0 || buildRandom >= 1000000) 13
    else 42
}
