#import("abla/compiler/parser")
#import("abla/io")

compile fun parseBuildInputDenied(
    cursor: ParserCursor
): SyntaxExpression {
    parserExpect(cursor, "{")
    parserExpect(cursor, "}")
    val contents = ablaHostReadFile(
        "tests/cases/capabilities/input.txt"
    )
    syntaxInteger(contents.size)
}

#compilerRegisterSubparser("deniedInput", parseBuildInputDenied)

fun main: int = $deniedInput{}
