val stagedBitwise = #(0xf0 & 0x3c)

fun main: int {
    if (stagedBitwise != 48) 1
    else if ((0xf0 | 0x0f) != 255) 2
    else if ((0xaa ^ 0xff) != 85) 3
    else if (~0 != -1) 4
    else if (1 << 8 != 256) 5
    else if (-8 >> 2 != -2) 6
    else if (-1 >>> 63 != 1) 7
    else if (1 << 64 != 0) 8
    else if (1 << -1 != 0) 9
    else if ((1 | (2 & 4)) != 1) 10
    else if (1 + 2 << 3 != 24) 11
    else 42
}
