import "../../../src/lexer.ab"

fun main: int {
    val source = "fun main { val text = \"ok\" }"
    val tokens = bootstrapLex(source)
    if (
        tokens.size == 11 &&
        tokens[0].kind == "fun" &&
        tokens[1].kind == "identifier" &&
        tokens[2].kind == "{" &&
        tokens[6].kind == "string-start" &&
        tokens[7].kind == "string-text" &&
        tokens[8].kind == "string-end" &&
        tokens[10].kind == "end"
    ) 42 else 0
}
