import "abla/compiler"

@client
fun answer(value: int): int = value + 1

compile fun configureCompiler(): void {
    val function = compiler.findFunction("answer")
    val annotated = compiler.functionsAnnotated("client")
    if (compiler.functions().size > 0 && annotated.size == 1 &&
        annotated[0] == function &&
        compiler.annotationCount(function) == 1 &&
        compiler.annotation(function, 0) == "client") {
        compiler.replaceFunctionBody(function, "value + 2")
    }
    return
}

#compiler.transform(configureCompiler)

fun main: int = answer(40)
