compile fun stagedChoice(flag: bool): int {
    var answer: int
    if (flag) {
        answer = 20
    } else {
        answer = 22
    }
    answer
}

fun runtimeChoice(flag: bool): int {
    var answer: int
    if (flag) {
        answer = 20
    } else {
        answer = 22
    }
    answer
}

fun main: int {
    if (
        #stagedChoice(true) + #stagedChoice(false) == 42 &&
        runtimeChoice(true) + runtimeChoice(false) == 42
    ) 42 else 0
}
