class Item(val value: int, var active: bool)
class Store(val items: array<Item>)

val numbers: array<int> = []
val state = Store([])
var replacement: array<int> = []

fun appendGlobalValues(): int {
    numbers.append(19)
    state.items.append(Item(23, true))
    val alias = state.items
    alias.append(Item(0, true))
    replacement = [42]
    numbers[0] + state.items[0].value + alias[1].value + replacement[0] - 42
}

fun main: int = appendGlobalValues()
