#import("abla/html")

fun main: int {
    val number = 20
    val runtime = $html <section><raw>A & B % done</raw><div>{number + 20}</div></section>
    val frozen = #$html <main><div>{20 + 20}</div></main>
    val runtimeText = runtime.querySelector("div").children[0].text
    val rawText = runtime.querySelector("raw").children[0].text
    val frozenText = frozen.querySelector("div").children[0].text
    if (
        runtimeText == "40" &&
        rawText == "A & B % done" &&
        frozenText == runtimeText
    ) 42 else 0
}
