class FirstDelegate(var value: int) {
    fun getValue(): int = value
    fun setValue(next: int): void {
        value = next
        return
    }
}

class SecondDelegate(var value: int) {
    fun getValue(): int = value
    fun setValue(next: int): void {
        value = next
        return
    }
}

fun main: int {
    var delegated by FirstDelegate(1)
    ^delegated = SecondDelegate(2)
    delegated
}
