import "abla/compiler"
import "abla/compiler/parser"

compile fun parseEarlyDependency(cursor: ParserCursor): SyntaxExpression {
    parserExpect(cursor, "(")
    val expression = parserParseAblaExpression(cursor)
    parserExpect(cursor, ")")
    typedExpressionReadCount(expression)
    expression
}

#compilerRegisterSubparser("earlyDependency", parseEarlyDependency)

fun main: int = $earlyDependency(40 + 2)
