#import("abla/compiler")
#import("abla/compiler/parser")

compile fun finalizeCollision(
    payload: string,
    expression: SyntaxExpression
): GeneratedModuleBuilder {
    val module = compilerGeneratedModule("invalid.collision", expression)
    val names: array<string> = []
    val types: array<int> = []
    compilerGeneratedExportFunction(
        module,
        "main",
        names,
        types,
        compilerFindType("int"),
        syntaxInteger(1)
    )
    module
}

compile fun parseCollision(cursor: ParserCursor): SyntaxExpression {
    parserExpect(cursor, "(")
    val expression = parserParseAblaExpression(cursor)
    parserExpect(cursor, ")")
    compilerRecordGeneratedExtensionRequest(
        "invalid.collision",
        "collision",
        expression,
        finalizeCollision
    )
    expression
}

#compilerRegisterSubparser("collision", parseCollision)

fun main: int = $collision(42)
