import "abla/json"

fun main: int {
    val frozen = #$json {"number": 20, "name": "abla"}
    val runtime = $json {"number": 20, "nested": [true, {"name": "abla"}]}
    val encoded = #$jsons {
        "number": 20,
        "nested": [true, {"name": "abla"}]
    }
    if (encoded != "{\"number\":20,\"nested\":[true,{\"name\":\"abla\"}]}") 1
    else if (frozen.getString("name") == runtime.at(1).at(1).getString("name")) {
        frozen.getInt("number") + runtime.getInt("number") + 2
    } else 0
}
