import "abla/unsafe/memory"

trusted fun main: int {
    val value = "\x00\x7f\x80\xff"
    val pointer = nativePointerFromAddress(nativeStringAddress(value))
    if (
        ablaUnsafeLoadU8(pointer) == 0 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 1)) == 127 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 2)) == 128 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 3)) == 255
    ) 42 else 1
}
