import "abla/unsafe/memory"

val bytes = nativeStaticBytes("\x00\x7f\x80\xff")

trusted fun main: int {
    val pointer = nativePointerFromAddress(bytes)
    if (
        ablaUnsafeLoadU8(pointer) == 0 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 1)) == 127 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 2)) == 128 &&
        ablaUnsafeLoadU8(ablaUnsafePointerOffset(pointer, 3)) == 255
    ) 42 else 1
}
