import "abla/compiler/parser"

compile fun parseBraced(cursor: ParserCursor): SyntaxExpression {
    parserExpect(cursor, "{")
    val expression = parserParseAblaExpression(cursor)
    parserExpect(cursor, "}")
    expression
}

compile fun parseParenthesized(cursor: ParserCursor): SyntaxExpression {
    parserExpect(cursor, "(")
    val expression = parserParseAblaExpression(cursor)
    parserExpect(cursor, ")")
    expression
}

#compilerRegisterSubparser("braced", parseBraced)
#compilerRegisterSubparser("parenthesized", parseParenthesized)
