#import("abla/compiler")
#import("abla/compiler/parser")

compile fun parseRawLiteral(cursor: ParserCursor): SyntaxExpression {
    parserRawSkipWhitespace(cursor)
    parserRawExpect(cursor, "<")
    val tag = parserRawTakeName(cursor)
    parserRawExpect(cursor, ">")
    parserRawTakeUntil(cursor, "<")
    parserRawExpect(cursor, "</")
    val closingTag = parserRawTakeName(cursor)
    parserRawExpect(cursor, ">")
    if (tag == "" || closingTag != tag) {
        parserFail(cursor, "raw literal tag mismatch")
    }
    syntaxInteger(42)
}

#compilerRegisterSubparser("rawLiteral", parseRawLiteral)
