import "abla/text"

fun main: int {
    val text = "Aé€😀"
    val invalid = "${text.slice(0, 2)}${text.slice(3, text.size)}"
    if (#utf8SequenceLength(240) == 4 &&
        #utf8DecodeAt("😀", 0) == 128512 && text.size == 10 &&
        text.isValidUtf8() && text.codePointCount() == 4 &&
        text.codePointAt(0) == 65 && text.codePointAt(1) == 233 &&
        text.codePointAt(2) == 8364 && text.codePointAt(3) == 128512 &&
        text.codePointAt(4) == -1 && text.codePointSlice(1, 3) == "é€" &&
        !invalid.isValidUtf8() && invalid.codePointCount() == -1) 42 else 0
}
