import "abla/unsafe/memory"

trusted fun clobberTemporaryStack(): void {
    val address = nativeStackAllocate(128)
    ablaUnsafeSetMemory(nativePointerFromAddress(address), 170, 128)
    return
}

trusted fun writeTemporaryValue(): int {
    val address = nativeStackAllocate(8)
    clobberTemporaryStack()
    val pointer = nativePointerFromAddress(address)
    ablaUnsafeSetMemory(pointer, 0, 8)
    ablaUnsafeStoreU16(pointer, 4660)
    ablaUnsafeStoreU32(ablaUnsafePointerOffset(pointer, 4), 2309737967)
    ablaUnsafeLoadU16(pointer) +
        ablaUnsafeLoadU32(ablaUnsafePointerOffset(pointer, 4))
}

fun main: int = writeTemporaryValue()
