trusted noescape extern:"intrinsic" fun nativeXtensaCoreId(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaCycleCounter(): int
trusted noescape extern:"intrinsic" fun nativeXtensaDelayCycles(
    cycles: int
): void
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptsEnable(
    mask: u32
): u32
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptsDisable(
    mask: u32
): u32
