trusted noescape extern:"intrinsic" fun nativeXtensaCoreId(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaCycleCounter(): int
trusted noescape extern:"intrinsic" fun nativeXtensaDelayCycles(
    cycles: int
): void
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptsEnable(
    mask: u32
): u32
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptsDisable(
    mask: u32
): u32
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptHandlerAddress(
    handler: Fn() -> void
): u32
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptTableAddress(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaExceptionTableAddress(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaInterruptLevelTableAddress(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaUnhandledInterruptAddress(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaUnhandledExceptionAddress(): u32
trusted noescape extern:"intrinsic" fun nativeXtensaOwnedDispatcherTableAddress(): u32
