import "abla/build"

val objectScheduled = #buildProgram(
    "program-object",
    "tests/cases/program-build/program-grandchild.ab",
    "build/programmable-build/program.o",
    "x86_64-linux",
    "object",
    true,
    false
)

val staticScheduled = #buildProgram(
    "program-static",
    "tests/cases/program-build/program-grandchild.ab",
    "build/programmable-build/libprogram.a",
    "x86_64-linux",
    "static-library",
    true,
    false
)

val sharedScheduled = #buildProgram(
    "program-shared",
    "tests/cases/program-build/exported-library.ab",
    "build/programmable-build/libabla_app.so",
    "x86_64-linux",
    "shared-library",
    true,
    false
)

fun main: int =
    if (objectScheduled && staticScheduled && sharedScheduled) 38 else 1
