#import("abla/compiler")
#import("artifact-slice-stateful-module-a.ab")

var serverSessions: int = 0

compile fun configureSlices(): void {
    compiler.defineTarget(
        "wasm32-module",
        "wasm32-unknown-unknown",
        "wasm",
        "wasm-ld",
        "none",
        false,
        true
    )
    compiler.contributeArtifactRoot(
        "client-slice-stateful-conflict",
        "wasm32-module",
        "module",
        "build/artifact-slice-stateful-conflict/client.wasm",
        compiler.findFunction("statefulClientInc"),
        "client_action",
        true,
        false
    )
    compiler.contributeArtifactRoot(
        "client-slice-stateful-conflict",
        "wasm32-module",
        "module",
        "build/artifact-slice-stateful-conflict/client.wasm",
        compiler.findFunction("unselectedStatefulClient"),
        "client_action",
        true,
        false
    )
    return
}

#compiler.transform(configureSlices)

fun main: int = serverSessions
