import "abla/build"

@export("abla_app_answer")
fun answer: int = 42

@export("abla_app_add")
fun add(value: int, delta: int): int = value + delta

@export("abla_app_bool_identity")
fun boolIdentity(value: bool): bool = value

@export("abla_app_i8_identity")
fun i8Identity(value: i8): i8 = value

@export("abla_app_u8_identity")
fun u8Identity(value: u8): u8 = value

@export("abla_app_char_identity")
fun charIdentity(value: char): char = value

@export("abla_app_i16_identity")
fun i16Identity(value: i16): i16 = value

@export("abla_app_u16_identity")
fun u16Identity(value: u16): u16 = value

@export("abla_app_i32_identity")
fun i32Identity(value: i32): i32 = value

@export("abla_app_u32_identity")
fun u32Identity(value: u32): u32 = value

@export("abla_app_i64_identity")
fun i64Identity(value: i64): i64 = value

@export("abla_app_u64_identity")
fun u64Identity(value: u64): u64 = value

@export("abla_app_bytes_score")
fun bytesScore(value: string): int = value.size + value[0]

@export("abla_app_bytes_length")
fun bytesLength(value: string): int = value.size

@export("abla_app_echo_bytes")
fun echoBytes(value: string): string = value

@export("abla_app_invoke")
fun invoke(callback: (int) -> int, value: int): int = callback(value)

@exportChecked("abla_app_checked_divide")
fun checkedDivide(value: int): int = 42 / value
