#import("abla/build")

fun answer: int = 42
fun add(value: int, delta: int): int = value + delta
fun bytesScore(value: string): int = value.size + value[0]
fun bytesLength(value: string): int = value.size
fun echoBytes(value: string): string = value
fun invoke(callback: (int) -> int, value: int): int = callback(value)
fun checkedDivide(value: int): int = 42 / value

val exported = #exportFunction(
    "answer",
    "abla_app_answer"
)

val addExported = #exportFunction(
    "add",
    "abla_app_add"
)

val bytesExported = #exportFunction(
    "bytesScore",
    "abla_app_bytes_score"
)

val bytesLengthExported = #exportFunction(
    "bytesLength",
    "abla_app_bytes_length"
)

val echoBytesExported = #exportFunction(
    "echoBytes",
    "abla_app_echo_bytes"
)

val invokeExported = #exportFunction(
    "invoke",
    "abla_app_invoke"
)

val checkedDivideExported = #exportCheckedFunction(
    "checkedDivide",
    "abla_app_checked_divide"
)
