import "abla/compiler"

val offset = 2

fun lifted(): int = 1 + offset

fun annotatedLift(): int = 5

compile fun buildIndependent(): void {
    if (compiler.functionsAnnotated("copied").size != 0) {
        compiler.newModule("")
    }
    val program = compiler.newModule("independent-module")
    program.use(compiler.function("annotatedLift").annotated("copied"))
    program.declare {
        compile fun verifyCopiedAnnotation(): void {
            val copied = compiler.functionsAnnotated("copied")
            if (copied.size == 1 &&
                compiler.functionName(copied[0]) == "annotatedLift") return
            compiler.addFunctionAnnotation(-1, "invalid")
            return
        }

        #verifyCopiedAnnotation()

        fun main: int = lifted() + annotatedLift()
    }
    program.emit("build/independent-module")
    return
}

#buildIndependent()

fun main: int = 0
