import "abla/compiler"

compile fun buildInvalidIndependent(): void {
    val program = compiler.newModule("invalid-independent-reference")
    program.use(compiler.function("doesNotExist"))
    program.declare {
        fun main: int = 0
    }
    program.emit(
        "build/invalid-independent-reference",
        target = "x86_64-linux"
    )
    return
}

#buildInvalidIndependent()

fun main: int = 0
