import "abla/sys/linux/process"

fun sleep(milliseconds: int): void = linuxSleep(milliseconds)

fun sleepNanoseconds(nanoseconds: int): bool =
    linuxSleepNanoseconds(nanoseconds)

fun monotonicNanoseconds(): int = linuxMonotonicNanoseconds()

fun monotonicMilliseconds(): int = linuxMonotonicMilliseconds()

resource class MonotonicClock(var linux: LinuxMonotonicClock) {
    fun valid(): bool = this.linux.valid()
    fun nanoseconds(): int = this.linux.nanoseconds()
    fun milliseconds(): int = this.nanoseconds() / 1000000
    fun sleepNanoseconds(nanoseconds: int): bool =
        this.linux.sleepNanoseconds(nanoseconds)

    fun drop(): void {
        this.linux.drop()
        return
    }
}

fun monotonicClock(): MonotonicClock {
    val clock = linuxMonotonicClock()
    MonotonicClock(move(clock))
}
