import "abla/build"
import "abla/json"
import "abla/unsafe/memory"

trusted fun allocate(length: int): int =
    nativePointerAddress(ablaUnsafeAllocate(length))

trusted fun storeAndLoad(pointer: int, value: int): int {
    val address = nativePointerFromAddress(pointer)
    ablaUnsafeStoreI64(address, value)
    ablaUnsafeLoadI64(address)
}

fun jsonLength: int {
    val response = $jsons {
        "status": 200,
        "body": "hello"
    }
    response.size
}

val allocateExported = #exportFunction(
    "allocate",
    "abla_wasm_allocate"
)

val storeAndLoadExported = #exportFunction(
    "storeAndLoad",
    "abla_wasm_store_and_load"
)

val jsonLengthExported = #exportFunction(
    "jsonLength",
    "abla_wasm_json_length"
)
