import "abla/build"
import "abla/unsafe/memory"

trusted fun allocate(length: int): int =
    nativePointerAddress(ablaUnsafeAllocate(length))

trusted fun storeAndLoad(pointer: int, value: int): int {
    val address = nativePointerFromAddress(pointer)
    ablaUnsafeStoreI64(address, value)
    ablaUnsafeLoadI64(address)
}

val allocateExported = #exportFunction(
    "allocate",
    "abla_wasm_allocate"
)

val storeAndLoadExported = #exportFunction(
    "storeAndLoad",
    "abla_wasm_store_and_load"
)
