#import("hello1.ab")

compiler fun from(name: string, decl: () => Unit) {
    1
}

extern:"abla_runtime" fun printi(value: int)
extern:"c" fun printf(fmt: string)

/*#from("abla_runtime") {
    extern fun printi(value: int)
    extern fun prints(str: string)
}*/

fun wrap(fn: (int) => int) {
    fn()
}

#{
    printf("hello")
}()

fun main {
    {
        4
    }()
    hi1()
    #printi(wrap {
        123
    })
    #printf("aad")
    #test(11)
}

fun test(a: int) => a