#import("hello1.ab")

compiler fun from(name: string, decl: () -> int): int {
    1
}

//extern:"abla_runtime" fun printi(value: int)
extern:"c" fun printf(fmt: string): int

/*#from("abla_runtime") {
    extern fun printi(value: int)
    extern fun prints(str: string)
}*/

fun wrap(fn: () -> int): int {
    fn()
}

#{
    printf("hi")
}()

compiler fun hello(a: int): int {
    printf("hiff $a\n")
}

fun voidReturn() {
    printf("Hello from void\n")
}

fun main: int {
    {
        4
    }()
    hi1()
    #hello(1)
    /*#printi(wrap {
        123
    })*/
    #printf("aad")
    printf("hello\u0020hi\n")
    voidReturn()
    if (fact(5) == 120) printf("fact(5) = 120\n") else printf("fact(5) != 120\n")
    assertValue("fact(4)", fact(4), 24, "expecting fact(4) to be 24\n")
    assertValue("fact(5)", fact(5), 121, "expecting fact(5) to be 120\n")
    #test(11) * 2
    div(2) > 2
}

fun fact(n: int):int = if (n > 1) n * fact(n - 1) else 1

fun assertValue(test: string, actual: int, expected: int, message: string) {
    if (actual == expected) {
        printf(test)
        printf(" ok\n")
    } else {
        printf(test)
        printf(" failed: ")
        printf(message)
    }
}

fun test(a: int): int = a
fun div(a: int): int = 8/a

/*class Chicken {
    fun quack: int = 1
}*/
