compiler abstract class Compiler {
    compiler abstract class Node {
        compiler abstract class Block
    }
}

compiler abstract class CompilerContext {
    abstract fun find(name: string): CompilerFunctionContext
    abstract fun modify<T>(name: string, func: () -> T)
    abstract fun setBody<T>(func: () -> T)
    abstract fun rename(newName: string)
    abstract fun defineInClass(func: () -> void)
}

compiler abstract class CompilerFunctionContext {
    abstract var block: Compiler.Node.Block
}
