#import("externals_common.ab")

fun voidReturn() {
    printf("Hello from void\n")
}

fun intReturn(): int = 1
fun intReturn2(): int { 1 }


fun forAux(n: int, m: int, fn: () -> int) : int {
    if (n >= 0) { fn() forAux(n - 1, m + 1, fn) } else 1
}

fun rudimentaryFor(start: int, end: int, fn: () -> int) : int {
    forAux(end - start, start, fn)
}

compiler fun hello(a: int): int {
    printf("hi $a\n")
}

fun test {
    voidReturn()
    if (intReturn() == 1) printf("Int return ok\n") else printf("Int return fail\n")
    if (intReturn2() == 1) printf("Int return ok\n") else printf("Int return fail\n")
    rudimentaryFor(1, 5) {
        printf("$")
    }
    printf("\n")
}

fun main {
    #test()
    #hello(1)
    test()
}