#import("externals_common.ab")

fun fact(n: int):int = if (n > 1) n * fact(n - 1) else 1

fun assertValue(test: string, actual: int, expected: int, message: string) {
    if (actual == expected) {
        printf(test)
        printf(" ok\n")
    } else {
        printf(test)
        printf(" failed: ")
        printf(message)
    }
}

fun test {
    if (fact(5) == 120) printf("fact(5) = 120\n") else printf("fact(5) != 120\n")
    assertValue("fact(4)", fact(4), 24, "expecting fact(4) to be 24\n")
    assertValue("fact(5)", fact(5), 120, "expecting fact(5) to be 120\n")
    printf("hello\u0020hi\n")
}

fun main {
    #test()
    test()
}