#import("externals_common.ab")
#import("stdlib.ab")

class Request(var remoteAddr: string)
class ILocationService
class API
class Inject
class Route(val route: string, val testInt: int)
class Version(val version: int)
class MyIPResponse(val address: string)
class MyIPResponseV2(val address: string, val location: string)

@Route("myip", 24)
class IPLookupAPI {
    var request: Request

    @Version(1)
    fun myip: MyIPResponse = MyIPResponse(this.request.remoteAddr)

    @Version(2)
    fun myip: MyIPResponseV2 = MyIPResponseV2(this.request.remoteAddr, "hi")
}

compiler fun annotationCheck(): int {
    val classDefinition = compilerContext.findClass("IPLookupAPI")
    //classDefinition.annotation<Route>().testInt // TODO make this actually work
    1
}

fun main: int {
    val api = IPLookupAPI()
    api.request = Request("123.123.123.123")
    printf(api.myip().address)
    #annotationCheck()
}

/*@Route("myip")
class IPLookupAPI(
  @Inject val locationService: ILocationService
) : API {
  @Version(1)
  fun myip = MyIPResponse(request.remoteaddr.toString())

  @Version(2)
  fun myip = previous().let {
    MyIPResponseV2(it.address, locationService.lookupLocation(it.address))
  }
}*/