#import("externals_common.ab")
#import("stdlib.ab")

class PacketId(val id: int)

class Packet

@PacketId(0x1)
class HandshakePacket /* : Packet() */

@PacketId(0x2)
class LoginPacket /* : Packet() */

@PacketId(0x3)
class PlayerInfoPacket /* : Packet() */

class PacketManager {
    /*val packetMapping = #{
        // Find all classes that inherit packet
        // Map packet id to constructor of specific class (to be able to construct incoming packets)
    }()*/
}

compile fun test() {
    val classDefinition = compilerContext.type<LoginPacket>()
    printf("${classDefinition.annotation<PacketId>().id}\n")
}

fun main {
    printf("Hi")
    #test()
}