#import("externals_common.ab")

fun test: int {
    {
        printf("Hi\n")
    }()

    testArg { arg: int ->
        arg * 2
    }
}

fun testArg(argFn: (int) -> int): int {
    argFn(6) + 5
}

fun testVoid(voidArgFun: (int) -> void) {
    voidArgFun(10)
}

fun main {
    #test()
    test()
    //val hello = { it: int -> 1 }
    //testVoid(hello) // TODO: make this throw error or infer
    testVoid { it: int ->
        printf("hi")
    }
}