#import("stdlib.ab")

fun call(): int = 1
extern:"c" fun printf(fmt: string): int
val a = 1
val b = 1
val c = #call()
fun test: int = 5

class Chicken {
    var a = 5
    val b = #test()
    val c = 1
    var d: string = "Hello this is a test string\n"
    fun quack(a: int): int = a + 10
    compiler fun test: int = 10
}

class TestConstruct(val a: int, val b: string) {
    fun test(): int = this.a + 5
}

fun main: int {
    val chicken: Chicken = Chicken()
    chicken.quack(32)
    chicken.a = chicken.b + chicken.c + #Chicken().quack(5)
    printf(chicken.d)
    val testClass: TestConstruct = TestConstruct(10, "another one\n")
    printf(testClass.b)
    chicken.a + testClass.test() + #TestConstruct(55, "another one\n").test()
}