#import("externals_common.ab")

fun test() {
    var a = 1
    var b = 2
    val c = a + b
    if (c == 3)
        printf("Var test: ok\n")
    else
        printf("Var test: fail\n")

    b = a = 5
    if (a == 5)
        printf("Var test 2: ok\n")
    else
        printf("Var test 2: fail\n")

    if (b == 5)
        printf("Var test 3: ok\n")
    else
        printf("Var test 3: fail\n")
}

fun main {
    #test()
    test()
}