fun call(): int = 1
extern:"c" fun printf(fmt: string): int
val a = 1
val b = 1
val c = #call()

class Chicken {
    var a = 5
    val b = 10
    val c = 4
    var d: string = "Hello this is a test string"
    fun quack(a: int): int = a + 10
    compiler fun test: int {
        1
    }
    #test()
}

fun main: int {
    val chicken: Chicken = Chicken()
    chicken.quack(32)
    chicken.a = chicken.b + chicken.c
    printf(chicken.d)
    chicken.a
}