#import("externals_common.ab")

extern:"c" fun fopen(file: string, mode: string): FILE*
extern:"c" fun fputs(str: string, stream: FILE*): int
extern:"c" fun fclose(stream: FILE*): int
extern:"c" fun fgets(str: string, n: int, stream: FILE*): string
extern:"c" fun fread(ptr: string, size: int, nmemb: int, stream: FILE*): int
extern:"c" fun malloc(n: int): string
extern:"c" fun free(ptr: string)
extern:"c" fun unlink(path: string): int
extern:"c" fun fprintf(stream: FILE*, fmt: string, param1: int): int
extern:"c" fun feof(stream: FILE*): int
extern:"c" fun memset(str: string, c: int, n: int): void*

class File(val fileName: string) {
    var file: FILE*
    fun open(mode: string): void {
        this.file = fopen(this.fileName, "w")
    }

    fun write(str: string) {
        fputs(str, this.file)
    }

    fun close() {
        fclose(this.file)
    }

    fun delete() {
        unlink(this.fileName)
    }
}

fun main {
    val fileName = "hello.txt"
    val file = fopen(fileName, "w")
    var a = 0
    while (a < 10) {
        fprintf(file, "hello %d\n", a)
        a = a + 1
    }
    fclose(file)

    val size = 100
    val buffer = malloc(size)
    val fileRead = fopen(fileName, "r")
    fread(buffer, size, 0, fileRead)
    printf(buffer)
    fclose(file)
    free(buffer)
    unlink(fileName)

    val testFile: File = File("hi.txt")
    testFile.open("w")
    testFile.write("ablac is awesome\n")
    testFile.close()
    testFile.delete()
}