#import("externals_common.ab")
#import("stdlib.ab")

class Request(var remoteAddr: string)
class ILocationService
class API
class Inject
class Route(val route: string)
class Version(val version: int)
class MyIPResponse(val address: string)
class MyIPResponseV2(val address: string, val location: string)

@Route("myip")
class IPLookupAPI {
    var request: Request

    fun myip: MyIPResponse = MyIPResponse(this.request.remoteAddr)
}

fun main {
    val api = IPLookupAPI()
    api.request = Request("123.123.123.123")
    printf(api.myip().address)
}

/*@Route("myip")
class IPLookupAPI(
  @Inject val locationService: ILocationService
) : API {
  @Version(1)
  fun myip = MyIPResponse(request.remoteaddr.toString())

  @Version(2)
  fun myip = previous().let {
    MyIPResponseV2(it.address, locationService.lookupLocation(it.address))
  }
}*/