import "abla/build"
import "abla/wasm/build"

val release = #wasmBuildModule(
    "same-process",
    "tests/cases/build-same-process/module.ab",
    "build/build-same-process/alone.wasm",
    false,
    false
)
val native = #buildProgram(
    "same-process-native",
    "tests/cases/build-same-process/module.ab",
    "build/build-same-process/alone.o",
    "host",
    "object",
    false,
    false
)

fun main: int = if (release && native) 0 else 1
